# Train an xgboost model based on Quadron feature (Quadron retrained) on active G4 dataset
# Script based on Elissar work on /media/ElissarDisk/Elissar/Projects/G4pred/Scripts/Scripts_R/AUROC/AUCROC_XGBoost_Quadron_trained.R
# Made by Vincent ROCHER (22/09/20)
library(keras) # To attribute value on multiple variables in one line
library(xgboost)
library(tidyverse)
library(Biostrings)
library(caret)  
#Load dataset (already splited)
# Data generated by scripts/data_generation/quadron_features_for_quadron_retrained.R
Quadron.train <- readRDS("rds/Quadron_features_Peaks_BG4_G4seq_HaCaT_GSE76688_hg19_201b_Ctrl_gkmSVM_0.8_42_Sequence_train.rds")

# set seed for reproductibility 
set.seed(1337)

X_train = xgb.DMatrix(as.matrix(Quadron.train %>%  select(-Y,-names)))
y_train = as.factor(as.matrix(Quadron.train %>% select(Y)))

# 
xgb_trcontrol = trainControl(method = "cv", number = 10, allowParallel = TRUE,
                             verboseIter = FALSE, returnData = FALSE)

xgbGrid <- expand.grid(nrounds = c(100,200),
                       max_depth = c(3, 5, 10, 15, 20),
                       colsample_bytree = seq(0.5, 0.9, length.out = 5),
                       ## values by default
                       eta = 0.1,
                       gamma=0,
                       min_child_weight = 1,
                       subsample = 1)

xgb_model = train( X_train,y_train, trControl = xgb_trcontrol, tuneGrid = xgbGrid, 
                   method = "xgbTree")
Params <- xgb_model$bestTune

# it make error if put X_train so put instead Quadron.train %>% select(-1)
xgb.train = xgb.DMatrix(data=as.matrix(Quadron.train %>%  select(-Y,-names)),label=as.matrix(y_train))
QModel <- xgb.train(as.list(Params) , xgb.train, nrounds = Params$nrounds)
xgb.save(QModel, "rds/Quadron_model_retrained_xgboost_Peaks_BG4_G4seq_HaCaT_GSE76688_hg19_201b_Ctrl_gkmSVM_0.8_42_Sequence_train.model")
#Some warnings when using parameters
# [10:19:05] WARNING: amalgamation/../src/learner.cc:516: 
#   Parameters: { nrounds } might not be used.
# 
# This may not be accurate due to some parameters are only used in language bindings but
# passed down to XGBoost core.  Or some parameters are not used but slip through this
# verification. Please open an issue if you find above cases.

# Predict outcomes with the test data
library(pROC)
Quadron.test <- readRDS("rds/Quadron_features_Peaks_BG4_G4seq_HaCaT_GSE76688_hg19_201b_Ctrl_gkmSVM_0.8_42_Sequence_test.rds")
y_test = as.factor(as.matrix(Quadron.test %>% select(Y)))
predSet <- xgb.DMatrix(data=as.matrix(Quadron.test %>%  select(-Y,-names)),label=as.matrix(y_test))
Model.Pred <- predict(QModel,predSet , reshape=T)

rocModel.Pred <- roc(as.factor(y_test),as.numeric(Model.Pred),ci=T)
aucModel.Pred  <- pROC::auc(rocModel.Pred)
pdf(paste0("results/Test_AUC_quadron_retrained.pdf"),width = 3, height = 3)
plot(rocModel.Pred, col = "black", main = paste0("AUC = ",round(aucModel.Pred , digits = 3)))
dev.off()



